-- Catálogo completo de movimientos de CrossFit. `nombre` ya es unique en
-- movimientos, así que ON CONFLICT DO NOTHING deja el seed idempotente
-- (se puede re-ejecutar sin duplicar ni pisar los 8 movimientos que ya
-- existían: Back Squat, Front Squat, Clean, Clean & Jerk, Jerk, Snatch,
-- Overhead Press, Deadlift).

insert into movimientos (nombre) values
  -- Barra olímpica / powerlifting
  ('Overhead Squat'),
  ('Sumo Deadlift'),
  ('Romanian Deadlift'),
  ('Deficit Deadlift'),
  ('Deadlift High Pull'),
  ('Power Clean'),
  ('Hang Clean'),
  ('Hang Power Clean'),
  ('Squat Clean'),
  ('Muscle Clean'),
  ('Clean Pull'),
  ('Push Jerk'),
  ('Split Jerk'),
  ('Power Jerk'),
  ('Power Snatch'),
  ('Hang Snatch'),
  ('Hang Power Snatch'),
  ('Squat Snatch'),
  ('Muscle Snatch'),
  ('Snatch Pull'),
  ('Snatch Balance'),
  ('Snatch Grip Deadlift'),
  ('Push Press'),
  ('Strict Press'),
  ('Bench Press'),
  ('Sots Press'),
  ('Good Morning'),
  ('Zercher Squat'),
  ('Thruster'),
  ('Front Rack Lunge'),
  ('Overhead Lunge'),
  ('Back Rack Lunge'),

  -- Gimnasia / peso corporal
  ('Pull-Up'),
  ('Chest-to-Bar Pull-Up'),
  ('Bar Muscle-Up'),
  ('Ring Muscle-Up'),
  ('Push-Up'),
  ('Handstand Push-Up'),
  ('Strict Handstand Push-Up'),
  ('Deficit Handstand Push-Up'),
  ('Handstand Walk'),
  ('Handstand Hold'),
  ('Toes-to-Bar'),
  ('Knees-to-Elbows'),
  ('Sit-Up'),
  ('GHD Sit-Up'),
  ('Back Extension'),
  ('Hip Extension'),
  ('Air Squat'),
  ('Pistol Squat'),
  ('Box Jump'),
  ('Box Jump Over'),
  ('Broad Jump'),
  ('Burpee'),
  ('Burpee Box Jump Over'),
  ('Burpee Pull-Up'),
  ('Bar Facing Burpee'),
  ('Dip'),
  ('Ring Dip'),
  ('Rope Climb'),
  ('L-Sit'),
  ('Wall Walk'),
  ('Tuck Jump'),
  ('Jumping Jack'),
  ('Lunge'),
  ('Walking Lunge'),
  ('Step-Up'),
  ('Plank'),
  ('V-Up'),
  ('Flutter Kick'),
  ('Ring Row'),
  ('Superman'),

  -- Kettlebell
  ('Kettlebell Swing (Russian)'),
  ('Kettlebell Swing (American)'),
  ('Kettlebell Snatch'),
  ('Kettlebell Clean'),
  ('Kettlebell Clean & Jerk'),
  ('Turkish Get-Up'),
  ('Goblet Squat'),

  -- Mancuernas
  ('Dumbbell Snatch'),
  ('Dumbbell Clean'),
  ('Dumbbell Clean & Jerk'),
  ('Dumbbell Power Clean'),
  ('Dumbbell Thruster'),
  ('Dumbbell Push Press'),
  ('Dumbbell Bench Press'),
  ('Dumbbell Overhead Squat'),
  ('Dumbbell Deadlift'),
  ('Dumbbell Walking Lunge'),
  ('2DB Devil Press'),
  ('Man Maker'),
  ('Renegade Row'),

  -- Monoestructural / cardio
  ('Run'),
  ('Row (Erg)'),
  ('Assault Bike'),
  ('Echo Bike'),
  ('Ski Erg'),
  ('Double Under'),
  ('Single Under'),

  -- Objetos y carga
  ('Wall Ball'),
  ('Sandbag Carry'),
  ('Sandbag Clean'),
  ('Sled Push'),
  ('Sled Pull'),
  ('Yoke Carry'),
  ('Farmers Carry'),
  ('Atlas Stone'),
  ('Tire Flip'),
  ('D-Ball Over Shoulder')
on conflict (nombre) do nothing;
